### PR TITLE
Set-ADAccountControl after Get-ADUser

### PR DESCRIPTION
**Pull request by kjake**
Set-ADAccountControl with a New-ADUser would not work in my environment

### CODE REVIEW

**Comment by infosystir** [comment]
> 

Hey @kjake, what OS version/patch level do you happen to be running at? Can you run that command by itself in powershell on the DC? We can try and replicate in our lab and fix the bug with more info :) Thanks!!

**Comment by kjake** [comment]
Hi!  I was running on a member server, not the DC.  The account would be created, but `Set-ADAccountControl -DoesNotRequirePreAuth $true` wouldn't take hold.  DC and Member server are 2019.  I re-ran on the DC itself and had the same result.  `Winnie_CvuVt` is the first account that I created with my PR command 2 days ago.

```powershell
PS C:\WINDOWS\system32> $user2
Winnie_YeCwZ
PS C:\WINDOWS\system32> New-ADUser -Name $user2 -GivenName "Winnie" -Surname "TP" -SamAccountName $user2 -AccountPassword $secPw -Enabled $true -ChangePasswordAtLogon $false | Set-ADAccountControl -DoesNotRequirePreAuth $true
PS C:\WINDOWS\system32> get-aduser -f * -pr DoesNotRequirePreAuth | where {$_.DoesNotRequirePreAuth -eq $TRUE}


DistinguishedName     : CN=Winnie_CvuVt,CN=Users,xxx,xxx
DoesNotRequirePreAuth : True
Enabled               : True
GivenName             : Winnie
Name                  : Winnie_CvuVt
ObjectClass           : user
ObjectGUID            : 1cee7a7e-e6cc-4745-95c6-f4e45723cd50
SamAccountName        : Winnie_CvuVt
SID                   : S-1-5-21-668404744-3322022041-74318029-8328
Surname               : TP
UserPrincipalName     :


PS C:\WINDOWS\system32> Get-ADUser $user2 | Set-ADAccountControl -DoesNotRequirePreAuth $true
PS C:\WINDOWS\system32> get-aduser -f * -pr DoesNotRequirePreAuth | where {$_.DoesNotRequirePreAuth -eq $TRUE}

DistinguishedName     : CN=Winnie_CvuVt,CN=Users,xxx,xxx
DoesNotRequirePreAuth : True
Enabled               : True
GivenName             : Winnie
Name                  : Winnie_CvuVt
ObjectClass           : user
ObjectGUID            : 1cee7a7e-e6cc-4745-95c6-f4e45723cd50
SamAccountName        : Winnie_CvuVt
SID                   : S-1-5-21-668404744-3322022041-74318029-8328
Surname               : TP
UserPrincipalName     :

DistinguishedName     : CN=Winnie_YeCwZ,CN=Users,xxx,xxx
DoesNotRequirePreAuth : True
Enabled               : True
GivenName             : Winnie
Name                  : Winnie_YeCwZ
ObjectClass           : user
ObjectGUID            : dc725672-7025-4615-aab0-173adb126fe1
SamAccountName        : Winnie_YeCwZ
SID                   : S-1-5-21-668404744-3322022041-74318029-8843
Surname               : TP
UserPrincipalName     :

```



Both systems report the same version of Powershell (I think this is the accurate way to find it).
```powershell
> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  2268
```

**Comment by infosystir** [comment]
> Hi! I was running on a member server, not the DC. The account would be created, but `Set-ADAccountControl -DoesNotRequirePreAuth $true` wouldn't take hold. DC and Member server are 2019. I re-ran on the DC itself and had the same result. `Winnie_CvuVt` is the first account that I created with my PR command 2 days ago.
> 
> ```powershell
> PS C:\WINDOWS\system32> $user2
> Winnie_YeCwZ
> PS C:\WINDOWS\system32> New-ADUser -Name $user2 -GivenName "Winnie" -Surname "TP" -SamAccountName $user2 -AccountPassword $secPw -Enabled $true -ChangePasswordAtLogon $false | Set-ADAccountControl -DoesNotRequirePreAuth $true
> PS C:\WINDOWS\system32> get-aduser -f * -pr DoesNotRequirePreAuth | where {$_.DoesNotRequirePreAuth -eq $TRUE}
> 
> 
> DistinguishedName     : CN=Winnie_CvuVt,CN=Users,xxx,xxx
> DoesNotRequirePreAuth : True
> Enabled               : True
> GivenName             : Winnie
> Name                  : Winnie_CvuVt
> ObjectClass           : user
> ObjectGUID            : 1cee7a7e-e6cc-4745-95c6-f4e45723cd50
> SamAccountName        : Winnie_CvuVt
> SID                   : S-1-5-21-668404744-3322022041-74318029-8328
> Surname               : TP
> UserPrincipalName     :
> 
> 
> PS C:\WINDOWS\system32> Get-ADUser $user2 | Set-ADAccountControl -DoesNotRequirePreAuth $true
> PS C:\WINDOWS\system32> get-aduser -f * -pr DoesNotRequirePreAuth | where {$_.DoesNotRequirePreAuth -eq $TRUE}
> 
> DistinguishedName     : CN=Winnie_CvuVt,CN=Users,xxx,xxx
> DoesNotRequirePreAuth : True
> Enabled               : True
> GivenName             : Winnie
> Name                  : Winnie_CvuVt
> ObjectClass           : user
> ObjectGUID            : 1cee7a7e-e6cc-4745-95c6-f4e45723cd50
> SamAccountName        : Winnie_CvuVt
> SID                   : S-1-5-21-668404744-3322022041-74318029-8328
> Surname               : TP
> UserPrincipalName     :
> 
> DistinguishedName     : CN=Winnie_YeCwZ,CN=Users,xxx,xxx
> DoesNotRequirePreAuth : True
> Enabled               : True
> GivenName             : Winnie
> Name                  : Winnie_YeCwZ
> ObjectClass           : user
> ObjectGUID            : dc725672-7025-4615-aab0-173adb126fe1
> SamAccountName        : Winnie_YeCwZ
> SID                   : S-1-5-21-668404744-3322022041-74318029-8843
> Surname               : TP
> UserPrincipalName     :
> ```
> 
> Both systems report the same version of Powershell (I think this is the accurate way to find it).
> 
> ```powershell
> > $PSVersionTable.PSVersion
> 
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 5      1      17763  2268
> ```

Awesome :) Thanks so much for the info! I'll get to the lab and start testing some more this week 😄

**Comment by infosystir** [comment]
> Hi! I was running on a member server, not the DC. The account would be created, but `Set-ADAccountControl -DoesNotRequirePreAuth $true` wouldn't take hold. DC and Member server are 2019. I re-ran on the DC itself and had the same result. `Winnie_CvuVt` is the first account that I created with my PR command 2 days ago.
> 
> ```powershell
> PS C:\WINDOWS\system32> $user2
> Winnie_YeCwZ
> PS C:\WINDOWS\system32> New-ADUser -Name $user2 -GivenName "Winnie" -Surname "TP" -SamAccountName $user2 -AccountPassword $secPw -Enabled $true -ChangePasswordAtLogon $false | Set-ADAccountControl -DoesNotRequirePreAuth $true
> PS C:\WINDOWS\system32> get-aduser -f * -pr DoesNotRequirePreAuth | where {$_.DoesNotRequirePreAuth -eq $TRUE}
> 
> 
> DistinguishedName     : CN=Winnie_CvuVt,CN=Users,xxx,xxx
> DoesNotRequirePreAuth : True
> Enabled               : True
> GivenName             : Winnie
> Name                  : Winnie_CvuVt
> ObjectClass           : user
> ObjectGUID            : 1cee7a7e-e6cc-4745-95c6-f4e45723cd50
> SamAccountName        : Winnie_CvuVt
> SID                   : S-1-5-21-668404744-3322022041-74318029-8328
> Surname               : TP
> UserPrincipalName     :
> 
> 
> PS C:\WINDOWS\system32> Get-ADUser $user2 | Set-ADAccountControl -DoesNotRequirePreAuth $true
> PS C:\WINDOWS\system32> get-aduser -f * -pr DoesNotRequirePreAuth | where {$_.DoesNotRequirePreAuth -eq $TRUE}
> 
> DistinguishedName     : CN=Winnie_CvuVt,CN=Users,xxx,xxx
> DoesNotRequirePreAuth : True
> Enabled               : True
> GivenName             : Winnie
> Name                  : Winnie_CvuVt
> ObjectClass           : user
> ObjectGUID            : 1cee7a7e-e6cc-4745-95c6-f4e45723cd50
> SamAccountName        : Winnie_CvuVt
> SID                   : S-1-5-21-668404744-3322022041-74318029-8328
> Surname               : TP
> UserPrincipalName     :
> 
> DistinguishedName     : CN=Winnie_YeCwZ,CN=Users,xxx,xxx
> DoesNotRequirePreAuth : True
> Enabled               : True
> GivenName             : Winnie
> Name                  : Winnie_YeCwZ
> ObjectClass           : user
> ObjectGUID            : dc725672-7025-4615-aab0-173adb126fe1
> SamAccountName        : Winnie_YeCwZ
> SID                   : S-1-5-21-668404744-3322022041-74318029-8843
> Surname               : TP
> UserPrincipalName     :
> ```
> 
> Both systems report the same version of Powershell (I think this is the accurate way to find it).
> 
> ```powershell
> > $PSVersionTable.PSVersion
> 
> Major  Minor  Build  Revision
> -----  -----  -----  --------
> 5      1      17763  2268
> ```

Hey! Sorry it took so long, it's been crazy :D This is all fixed now!

**Pull request closed without merging**
