### PR TITLE
Modified to aid in detection for AS-REP Roasting

### PR DESCRIPTION
**Pull request by infosystir**

### CODE REVIEW

**Comment by mwarnerblu** [comment]
Does this maintain the existing Kerberoast detection generally or is intended to be used separately? I would need to test but without the Set-SPN I'm unsure if you'd only get AS-REP detection and not Kerberoast. 

https://github.com/Blumira/Kerberoast-Detection/blob/5a305318a3cd8f3c557da60d96d4fdb9b8fa805a/DOGEMIRA.ps1#L65-L67

**Comment by infosystir** [comment]
> Does this maintain the existing Kerberoast detection generally or is intended to be used separately? I would need to test but without the Set-SPN I'm unsure if you'd only get AS-REP detection and not Kerberoast.
> 
> https://github.com/Blumira/Kerberoast-Detection/blob/5a305318a3cd8f3c557da60d96d4fdb9b8fa805a/DOGEMIRA.ps1#L65-L67

The first user is for the kerberoast detection, as it's the service account creation and SPN, the second user is for as-rep with the flag of "-DoesNotRequierPreaAuth" being set to true

**Comment by mwarnerblu** [comment]
Ah I gotcha, let me test real quick!

**Comment by mwarnerblu** [comment]
LGTM in testing, ready for release.

```
PS C:\Users\mwarner\Downloads> Set-ExecutionPolicy Unrestricted; .\DOGEMIRA.ps1

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Users\mwarner\Downloads\DOGEMIRA.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): R
Checking domain DC=logtestdc,DC=intra

Registering ServicePrincipalNames for CN=DefaultAppPool_wSyxR,CN=Users,DC=logtestdc,DC=intra
        IIS_IUSRSB_NdPsh/portal.logtestdc.intra:80
Updated object
```

**Review by mwarnerblu — APPROVED** [review]
LGTM

**Pull request merged**
